name = "MyExample"
uuid = "f9adebf2-4efe-4d1c-8447-c5ef853d76cf"
authors = ["Gianluca Grosso <gianluca.grosso@campus.lmu.de> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
LinearAlgebra = "1.7"
Statistics = "1.7"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
